import './globals.css';
import Navbar from './components/navbar/Navbar';
import Footer from './components/footer/Footer';

export const metadata = {
  title: 'Byte Height',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Navbar />
        </header>
          <main>
            <div className='container mx-auto'>
              {children}
            </div>
          </main>
        <Footer />
      </body>
    </html>
  )
}
