import './globals.css';
import Navbar from './components/navbar/Navbar';
import Footer from './components/footer/Footer';

export const metadata = {
  title: 'Byte Height',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className='pb-7'>
          <Navbar />
        </header>
          <main className='h-screen'>
            <div className='container h-full mx-auto px-2'>
              {children}
            </div>
          </main>
        <Footer />
      </body>
    </html>
  )
}
